name: Change variable status

on:
  push:
    branches:
      - main

jobs:
  change_variable_status:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: change value
        run: ${{ env.ENV_DEPLOYMENT_STATUS = "PENDING" }}
