name: Check variable value

on:
  pull_request:
    branches:
      - main

jobs:
  change_variable_status:
    runs-on: ubuntu-latest
    steps:
      - name: Fail on bad status
        if: ${{ vars.ENV_DEPLOYMENT_STATUS != 'SUCCESS' }}
        run: |
          echo "Variable not in the correct state"
          exit 1

